name: "Submit"

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    
permissions:
  contents: read

jobs:
  submit:
    runs-on: windows-latest

    steps:  
      - name: Submit Notification
        if: ${{ success() }}
        run: |
          $DISCORD_SUBMIT_WEBHOOK_URL = "${{ secrets.DISCORD_SUBMIT_WEBHOOK_URL }}"
          $commitMessage = "${{ github.event.head_commit.message }}"
          $repo = "${{ github.repository }}"
          $commitSha = "${{ github.sha }}"
          $commitUrl = "https://github.com/$repo/commit/$commitSha"
          
          $jsonPayload = @"
          {
            "username": "GitHub",
            "content": "",
            "embeds": [
              {
                "type": "rich",
                "title": "New Submit",
                "description": "$commitMessage",
                "color": 38912,
                "thumbnail": {
                  "url": "https://github.com/vimontgames/vgframework/blob/master/doc/img/newsubmit.png?raw=true"
                },
                "author": {
                  "name": "$($env:GITHUB_ACTOR)",
                  "url": "https://github.com/$($env:GITHUB_ACTOR)",
                  "icon_url": "https://avatars.githubusercontent.com/u/$($env:GITHUB_ACTOR_ID)?v=4"
                },
                "url": "$commitUrl"
              }
            ]
          }
          "@
      
          $RESPONSE = curl -H "Content-Type: application/json" -X POST -d $jsonPayload $DISCORD_SUBMIT_WEBHOOK_URL
          Write-Output "Webhook server response: $RESPONSE"
