name: "Submit"

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    
permissions:
  contents: read

jobs:
  submit:
    runs-on: windows-latest

    steps:  
      - name: Submit Notification
        if: ${{ success() }}
        run: |
          $DISCORD_SUBMIT_WEBHOOK_URL = "${{ secrets.DISCORD_SUBMIT_WEBHOOK_URL }}"
          $commitMessage = "${{ github.event.head_commit.message }}"
          $repo = "${{ github.repository }}"
          $commitSha = "${{ github.sha }}"
          $shortCommitSha = $commitSha.Substring(0, 7)
          $commitUrl = "https://github.com/$repo/commit/$commitSha"

          Write-Output "Commit message: $commitMessage"

          # Escape commitMessage to ensure it works within JSON
          $escapedCommitMessage = $commitMessage -replace '"', '\"' -replace "`r`n", '\n' -replace "`n", '\n'

          Write-Output "Escaped commit message: $escapedCommitMessage"

          # Split the commit message into summary and description based on \n\n
          $splitMessage = $escapedCommitMessage -split '\n{2,}', 2
          
          # Ensure summary and description are handled correctly
          $summary = $splitMessage[0]
          $description = if ($splitMessage.Length -gt 1) { $splitMessage[1] } else { "" }

          $title = "$summary ($shortCommitSha)"

          Write-Output "Summary: $summary"
          Write-Output "Description: $description"
          
          $jsonPayload = @"
          {
            "username": "Freaky clown",
            "content": "",
            "embeds": [
              {
                "type": "rich",
                "title": "$title",
                "description": "$description",
                "color": 7542970,
                "thumbnail": {
                  "url": "https://github.com/vimontgames/vgframework/blob/master/doc/img/newsubmit.png?raw=true"
                },
                "author": {
                  "name": "$($env:GITHUB_ACTOR)",
                  "url": "https://github.com/$($env:GITHUB_ACTOR)",
                  "icon_url": "https://avatars.githubusercontent.com/u/$($env:GITHUB_ACTOR_ID)?v=4"
                }
                "url": "$commitUrl"
              }
            ]
          }
          "@

          Write-Output "JSON playload: $jsonPayload"
      
          $RESPONSE = curl -H "Content-Type: application/json" -X POST -d $jsonPayload $DISCORD_SUBMIT_WEBHOOK_URL
          Write-Output "Webhook server response: $RESPONSE"
